function pressure = import_pressure(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PRESSURE = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  PRESSURE = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  pressure = importfile("/home/yobh/Desktop/LANL/PsDNS/caso_buoyant/data/pressure.dat", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Apr-2025 20:51:18

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "z", "p", "prms", "pu", "pv", "pw", "pc", "pdudx", "pdudy", "pdudz", "pdvdx", "pdvdy", "pdvdz", "pdwdx", "pdwdy", "pdwdz", "VarName18", "VarName19"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
pressure = readtable(filename, opts);

%% Convert to output type
pressure = table2array(pressure);
end